apiVersion: v2
version: 0.2.0

name: reactor
type: library
description: A shared library for Helm chart resources.
home: https://github.com/kube-reactor/charts

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    version: 2.31.1
    tags:
      - bitnami-common

maintainers:
  - email: adrian@fractalsynapse.com
    name: adrianwebb
    url: https://github.com/adrianwebb
