{{/*
Create chart name and version as used by the chart label
*/}}
{{- define "reactor.chart" -}}
{{- include "common.names.chart" . -}}
{{- end -}}

{{/*
Selector labels
*/}}
{{- define "reactor.selectorLabels" -}}
{{- $root := (index . 0) -}}
{{- $service := (index . 1) -}}
{{- $name := (index . 2) -}}
app.kubernetes.io/name: {{ include "reactor.name" $root | quote }}
app.kubernetes.io/instance: {{ $root.Release.Name | quote }}
app.kubernetes.io/component: {{ include "reactor.serviceName" (list $root $service $name) | quote }}
{{- end -}}

{{/*
Service labels
*/}}
{{- define "reactor.labels" -}}
{{- $root := (index . 0) -}}
{{- $service := (index . 1) -}}
{{- $name := (index . 2) -}}
helm.sh/chart: {{ include "reactor.chart" $root | quote }}
{{- if $root.Chart.AppVersion }}
app.kubernetes.io/version: {{ $root.Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ $root.Release.Service }}
{{ include "reactor.selectorLabels" (list $root $service $name) }}
{{ $labels := ternary (merge ($service.labels | default (dict )) $root.Values.labels) $root.Values.labels (not (empty $service)) -}}
{{- range $key, $value := $labels -}}
{{ $key }}: {{ $value | quote }}
{{- end -}}
{{- if $service.backup -}}
recurring-job.longhorn.io/source: enabled
recurring-job.longhorn.io/backup: enabled
{{- end -}}
{{- end -}}

