apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
  labels:
    {{- include "coredns-config.labels" . | nindent 4 }}
data:
{{- with .Values.overrides }}
{{ toYaml . | nindent 4}}
{{- end }}
{{- with .Values.servers }}
{{ toYaml . | nindent 4}}
{{- end }}