apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
  labels:
    {{- include "coredns-config.labels" . | nindent 4 }}
data:
{{- if .Values.hosts }}
    hosts.override: |
      hosts /etc/coredns/NodeHosts {
        {{- range .Values.hosts }}
        {{ .ip }} {{ .name }}
        {{- end }}
        ttl 60
        reload 15s
        fallthrough
      }
{{- end }}

{{- with .Values.servers }}
{{ toYaml . | nindent 4}}
{{- end }}