apiVersion: v2
version: 2.0.0
appVersion: 0.0.0

name: application
type: application
description: A Helm chart for deploying flexible applications.
home: https://github.com/kube-reactor/charts

dependencies:
  - name: reactor
    repository: https://charts.kube-reactor.com
    version: 0.x.x

maintainers:
  - email: adrian@fractalsynapse.com
    name: adrianwebb
    url: https://github.com/adrianwebb
